# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

build_number = (ENV["BUILD_NUMBER"] || "1").to_i || 1

default_platform(:ios)

platform :ios do

  desc "Firebase App Distribution"
  lane :firebase do

      increment_build_number(
        build_number: build_number + 1,
      )

      build_app(
        workspace: "RNFastlanePratice.xcworkspace",
        scheme: "RNFastlanePratice",
        include_bitcode: false,
        export_options: {
            uploadBitcode: false,
            uploadSymbols: true,
            compileBitcode: false
        },
        output_directory: './output',
      )
      # build_ios_app is a built-in fastlane action.

      firebase_app_distribution(
          # your firebase project
          app: "1:1234567890:ios:0a1b2c3d4e5f67890",

          firebase_cli_token: ENV["FIREBASE_TOKEN"],
          groups: "product",
          release_notes_file: "./releasenotes.txt",
      )

  end

  desc "Testflight"
  lane :testflight do

      increment_build_number(
        build_number: build_number + 1,
      )

      sync_code_signing(type: "appstore")

      build_app(
        workspace: "RNFastlanePratice.xcworkspace",
        scheme: "RNFastlanePratice",
        include_bitcode: false,
        export_options: {
            uploadBitcode: false,
            uploadSymbols: true,
            compileBitcode: false
        },
        output_directory: './output',
      )
      # build_ios_app is a built-in fastlane action.

      upload_to_testflight

  end
end

lane :print_build_number do
  puts("current build number is #{build_number}")
end